WALK_UP = 4
WALK_DOWN = 3
WALK_RIGHT = 2
WALK_LEFT = 1

NO_OP = 0

SHOOT = 5

WALK_ACTIONS = [WALK_UP, WALK_DOWN, WALK_RIGHT, WALK_LEFT]
ACTIONS = [NO_OP, WALK_LEFT, WALK_RIGHT, WALK_DOWN, WALK_UP, SHOOT]
